const REGIONS = {
  "north-america": [
    "north america",
    "na",
    "n-america",
    "the americas",
    "america",
    "usa",
    "united states",
    "us",
    "u.s.",
    "canada",
    "mexico",
    "greenland",
    "bermuda",
    "bahamas",
    "cuba",
    "jamaica",
    "haiti",
    "dominican republic",
    "puerto rico",
    "belize",
    "guatemala",
    "el salvador",
    "honduras",
    "nicaragua",
    "costa rica",
    "panama",
  ],
  "south-america": [
    "south america",
    "sa",
    "latam",
    "brazil",
    "argentina",
    "colombia",
    "chile",
    "peru",
    "venezuela",
    "ecuador",
    "bolivia",
    "paraguay",
    "uruguay",
    "guyana",
    "suriname",
    "french guiana",
  ],
  europe: [
    "europe",
    "eu",
    "united kingdom",
    "france",
    "germany",
    "italy",
    "spain",
    "portugal",
    "netherlands",
    "belgium",
    "luxembourg",
    "switzerland",
    "austria",
    "denmark",
    "norway",
    "sweden",
    "finland",
    "iceland",
    "ireland",
    "poland",
    "czech republic",
    "slovakia",
    "hungary",
    "romania",
    "bulgaria",
    "greece",
    "serbia",
    "croatia",
    "slovenia",
    "bosnia and herzegovina",
    "montenegro",
    "albania",
    "north macedonia",
    "estonia",
    "latvia",
    "lithuania",
    "malta",
    "cyprus",
    "ukraine",
    "belarus",
    "moldova",
    "russia",
  ],
  asia: [
    "asia",
    "as",
    "china",
    "india",
    "japan",
    "south korea",
    "north korea",
    "pakistan",
    "bangladesh",
    "indonesia",
    "philippines",
    "vietnam",
    "thailand",
    "myanmar",
    "nepal",
    "sri lanka",
    "malaysia",
    "singapore",
    "laos",
    "cambodia",
    "mongolia",
    "taiwan",
    "afghanistan",
    "iran",
    "iraq",
    "saudi arabia",
    "uae",
    "qatar",
    "kuwait",
    "bahrain",
    "oman",
    "yemen",
    "turkey",
    "georgia",
    "armenia",
    "azerbaijan",
    "syria",
    "lebanon",
    "jordan",
    "israel",
  ],
  africa: [
    "africa",
    "af",
    "northafrica",
    "westafrica",
    "eastafrica",
    "centralafrica",
    "southernafrica",
    "egypt",
    "libya",
    "tunisia",
    "algeria",
    "morocco",
    "sudan",
    "south sudan",
    "mauritania",
    "mali",
    "niger",
    "chad",
    "senegal",
    "gambia",
    "guinea",
    "guinea-bissau",
    "sierra leone",
    "liberia",
    "côte d'ivoire",
    "ghana",
    "burkina faso",
    "togo",
    "benin",
    "cameroon",
    "central african republic",
    "equatorial guinea",
    "gabon",
    "congo",
    "democratic republic of the congo",
    "angola",
    "zambia",
    "malawi",
    "mozambique",
    "namibia",
    "botswana",
    "zimbabwe",
    "south africa",
    "lesotho",
    "eswatini",
    "tanzania",
    "uganda",
    "kenya",
    "rwanda",
    "burundi",
    "djibouti",
    "eritrea",
    "ethiopia",
    "somalia",
    "cape verde",
    "seychelles",
    "comoros",
    "madagascar",
    "mauritius",
    "sao tome and principe",
  ],
  australia: [
    "australia",
    "au",
    "oceania",
    "pacific",
    "new zealand",
    "nz",
    "australia",
    "new zealand",
    "papua new guinea",
    "fiji",
    "solomon islands",
    "vanuatu",
    "samoa",
    "tonga",
    "micronesia",
    "marshall islands",
    "palau",
    "kiribati",
    "tuvalu",
    "nauru",
  ],
};

// Levenshtein distance
function levenshtein(a, b) {
  const matrix = Array.from({ length: b.length + 1 }, (_, i) => [i]);
  for (let j = 0; j <= a.length; j++) matrix[0][j] = j;

  for (let i = 1; i <= b.length; i++) {
    for (let j = 1; j <= a.length; j++) {
      if (b[i - 1] === a[j - 1]) matrix[i][j] = matrix[i - 1][j - 1];
      else matrix[i][j] = Math.min(
        matrix[i - 1][j] + 1,
        matrix[i][j - 1] + 1,
        matrix[i - 1][j - 1] + 1
      );
    }
  }
  return matrix[b.length][a.length];
}

// Find closest match
module.exports = (alias) => {
  const lower = alias.toLowerCase().trim();
  let closestRegion = null;
  let smallestDistance = Infinity;

  for (const [region, aliases] of Object.entries(REGIONS)) {
    for (const name of aliases) {
      const distance = levenshtein(lower, name.toLowerCase());
      if (distance < smallestDistance) {
        smallestDistance = distance;
        closestRegion = region;
      }
    }
  }

  return closestRegion;
}