import { useMutation, useQuery, useQueryClient } from '@/lib/query';
import { AlertTriangle, Anchor, BellRing, ChevronDown, Compass, DoorOpen, LayoutDashboard, LoaderCircle, Menu, Network, Plus, Radio, Search, Settings, ShieldBan, ShipWheel, Trash2, Users, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useForm } from '@/lib/form';
import { Link, navigate, usePath } from '@/lib/router';
import { toast } from '@/lib/toast';
import { Badge, Skeleton } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input, Label, Textarea } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import { Brand } from '@/pages/Landing';
import { cn } from '@/lib/utils';
import {
  addBan, ApiError, api, createDock, deleteDock, deleteFollow, getBans, getDocks, getFollowers, getGuild, getGuilds, getMe,
  removeBan, saveFollow, saveSettings, setFollowerLevel, updateDock,
  type Ban, type Dock, type Follow, type Guild, type GuildData, type GuildSummary, type PingGroup, type Role,
} from '@/lib/api';

const sections = [
  { id: 'overview', label: 'Overview', icon: LayoutDashboard },
  { id: 'settings', label: 'Server settings', icon: Settings },
  { id: 'pings', label: 'Ping groups', icon: BellRing },
  { id: 'docks', label: 'Docks', icon: Network },
];
const dockLevels = ['no-access', 'passive', 'sender', 'contributor', 'admin'];
const levelLabels: Record<string, string> = { 'no-access': 'Pending / no access', passive: 'Passive', sender: 'Sender', contributor: 'Contributor', admin: 'Admin' };

function SelectField({ label, value, onChange, children, disabled, hint }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode; disabled?: boolean; hint?: string }) {
  return <div className="space-y-2"><Label>{label}</Label><div className="relative"><select className="select-field" value={value} onChange={(event) => onChange(event.target.value)} disabled={disabled}>{children}</select><ChevronDown className="pointer-events-none absolute right-3 top-3.5 size-4 text-slate-500" /></div>{hint && <p className="text-xs text-slate-500">{hint}</p>}</div>;
}

function Empty({ icon: Icon = Compass, title, copy, action }: { icon?: React.ElementType; title: string; copy: string; action?: React.ReactNode }) {
  return <div className="grid min-h-64 place-items-center rounded-2xl border border-dashed border-white/10 bg-white/[.015] p-8 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-xl bg-white/[.05] text-slate-400"><Icon className="size-5" /></span><h3 className="mt-4 font-display text-xl text-white">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-400">{copy}</p>{action && <div className="mt-5">{action}</div>}</div></div>;
}

function ErrorState({ error, retry }: { error: Error; retry?: () => void }) {
  return <Card className="border-rose-400/15 p-6"><div className="flex gap-4"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-rose-300" /><div><h3 className="font-semibold text-white">Couldn’t load this view</h3><p className="mt-1 text-sm text-slate-400">{error.message}</p>{retry && <Button size="sm" variant="secondary" className="mt-4" onClick={retry}>Try again</Button>}</div></div></Card>;
}

function ServerChooser({ guilds }: { guilds: GuildSummary[] }) {
  return <div className="min-h-screen bg-[#061217] px-5 py-12 text-white"><div className="mx-auto max-w-4xl"><Brand /><div className="mt-20 max-w-xl"><p className="eyebrow">Dashboard</p><h1 className="font-display text-4xl font-semibold sm:text-5xl">Choose a server to manage.</h1><p className="mt-4 leading-7 text-slate-400">Only servers where Sailor’s Lodge is installed and you have management permissions appear here.</p></div>{guilds.length ? <div className="mt-10 grid gap-3 sm:grid-cols-2">{guilds.map((guild) => <Link key={guild.id} to={`/dashboard/${guild.id}/overview`} className="group flex items-center gap-4 rounded-2xl border border-white/[.08] bg-white/[.025] p-5 transition hover:-translate-y-0.5 hover:border-teal-200/20 hover:bg-teal-200/[.04]"><GuildIcon guild={guild} /><div className="min-w-0"><div className="truncate font-semibold text-white">{guild.name}</div><div className="mt-1 text-xs text-slate-500">{guild.owner ? 'Owner' : guild.manageGuild && guild.manageChannels ? 'Manage Server & Channels' : guild.manageGuild ? 'Manage Server' : 'Manage Channels'}</div></div><ChevronDown className="ml-auto size-4 -rotate-90 text-slate-600 transition group-hover:text-teal-200" /></Link>)}</div> : <div className="mt-10"><Empty title="No manageable servers found" copy="Add Sailor’s Lodge to a server or ask an owner for the required Discord permission." action={<Button asChild><a href="/invite">Add to Discord</a></Button>} /></div>}</div></div>;
}

function GuildIcon({ guild, className }: { guild: Pick<GuildSummary, 'name' | 'icon'>; className?: string }) {
  return guild.icon ? <img src={guild.icon} alt="" className={cn('size-10 rounded-xl object-cover', className)} /> : <span className={cn('grid size-10 place-items-center rounded-xl bg-teal-200/10 font-display font-semibold text-teal-100', className)}>{guild.name.slice(0, 2).toUpperCase()}</span>;
}

function Shell({ user, guilds, data, section, children }: { user: { username: string; avatar: string | null }; guilds: GuildSummary[]; data: GuildData; section: string; children: React.ReactNode }) {
  const [mobile, setMobile] = useState(false);
  return <div className="min-h-screen bg-[#061217] text-slate-100">
    <aside className={cn('fixed inset-y-0 left-0 z-40 w-72 border-r border-white/[.07] bg-[#07171c]/95 p-5 backdrop-blur-xl transition-transform lg:translate-x-0', mobile ? 'translate-x-0' : '-translate-x-full')}>
      <div className="flex items-center justify-between"><Brand /><Button size="icon" variant="ghost" className="lg:hidden" onClick={() => setMobile(false)} aria-label="Close navigation"><X className="size-5" /></Button></div>
      <div className="mt-8"><Label className="mb-2 block text-xs uppercase tracking-[.14em] text-slate-500">Server</Label><div className="relative"><select aria-label="Server" className="select-field h-14 pl-14" value={data.guild.id} onChange={(event) => navigate(`/dashboard/${event.target.value}/overview`)}>{guilds.map((guild) => <option key={guild.id} value={guild.id}>{guild.name}</option>)}</select><GuildIcon guild={data.guild} className="absolute left-2 top-2 size-10" /><ChevronDown className="pointer-events-none absolute right-3 top-5 size-4 text-slate-500" /></div></div>
      <nav className="mt-8 space-y-1" aria-label="Dashboard navigation">{sections.map(({ id, label, icon: Icon }) => <Link key={id} to={`/dashboard/${data.guild.id}/${id}`} onClick={() => setMobile(false)} className={cn('flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition', section === id ? 'bg-teal-200/[.09] text-teal-100 ring-1 ring-inset ring-teal-200/10' : 'text-slate-400 hover:bg-white/[.04] hover:text-white')}><Icon className="size-4.5" />{label}</Link>)}</nav>
      <div className="absolute inset-x-5 bottom-5"><div className="flex items-center gap-3 border-t border-white/[.07] pt-5">{user.avatar ? <img src={user.avatar} alt="" className="size-9 rounded-full" /> : <span className="grid size-9 place-items-center rounded-full bg-white/10">{user.username[0]}</span>}<div className="min-w-0"><p className="truncate text-sm font-medium text-white">{user.username}</p><button className="text-xs text-slate-500 hover:text-slate-300" onClick={async () => { await api('/auth/logout', { method: 'POST', body: '{}' }); window.location.href = '/'; }}>Sign out</button></div></div></div>
    </aside>
    {mobile && <button className="fixed inset-0 z-30 bg-black/60 lg:hidden" onClick={() => setMobile(false)} aria-label="Close navigation overlay" />}
    <div className="lg:pl-72"><header className="sticky top-0 z-20 flex h-17 items-center gap-4 border-b border-white/[.06] bg-[#061217]/80 px-5 backdrop-blur-xl sm:px-8"><Button size="icon" variant="ghost" className="lg:hidden" onClick={() => setMobile(true)} aria-label="Open navigation"><Menu className="size-5" /></Button><div><p className="text-xs text-slate-500">{data.guild.name}</p><h1 className="font-display text-lg font-semibold capitalize text-white">{sections.find((item) => item.id === section)?.label || 'Overview'}</h1></div><Badge className="ml-auto hidden sm:inline-flex">Connected</Badge></header><main className="mx-auto max-w-7xl p-5 sm:p-8 lg:p-10">{children}</main></div>
  </div>;
}

function Overview({ data }: { data: GuildData }) {
  const ready = Boolean(data.settings.lfgRoleId) && data.settings.pingGroups.length > 0;
  const stats = [
    { label: 'Ping groups', value: data.settings.pingGroups.length, icon: BellRing, href: 'pings' },
    { label: 'Published Docks', value: data.counts.published, icon: Radio, href: 'docks' },
    { label: 'Following', value: data.counts.following, icon: Network, href: 'docks' },
  ];
  return <div className="space-y-8"><div className="max-w-2xl"><p className="eyebrow">Welcome aboard</p><h2 className="font-display text-3xl font-semibold text-white sm:text-4xl">Your community at a glance.</h2><p className="mt-3 text-slate-400">Configure how players find groups and how this server connects to the wider network.</p></div><div className="grid gap-4 md:grid-cols-3">{stats.map(({ label, value, icon: Icon, href }) => <Link to={`../${href}`} key={label}><Card className="group p-6 transition hover:-translate-y-0.5 hover:border-teal-200/20"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">{label}</p><p className="mt-2 font-display text-4xl text-white">{value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-teal-200/[.07] text-teal-200"><Icon className="size-4.5" /></span></div></Card></Link>)}</div><Card><CardHeader><div className="flex items-center gap-3"><span className={cn('size-2.5 rounded-full', ready ? 'bg-teal-300' : 'bg-amber-300')} /><CardTitle>Setup checklist</CardTitle></div><CardDescription>A few durable settings make every command smoother for your members.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3">{[
    ['Choose an LFG role', Boolean(data.settings.lfgRoleId), 'settings'], ['Create a ping group', data.settings.pingGroups.length > 0, 'pings'], ['Publish or follow a Dock', data.counts.published + data.counts.following > 0, 'docks'],
  ].map(([label, done, href]) => <Link key={String(label)} to={`../${href}`} className="flex items-center gap-3 rounded-xl border border-white/[.07] bg-white/[.02] p-4 text-sm"><span className={cn('grid size-6 place-items-center rounded-full text-xs', done ? 'bg-teal-300 text-slate-950' : 'border border-white/15 text-slate-500')}>{done ? '✓' : '·'}</span><span className={done ? 'text-slate-400 line-through' : 'text-slate-200'}>{label}</span></Link>)}</CardContent></Card></div>;
}

function ServerSettings({ data, refresh }: { data: GuildData; refresh: () => void }) {
  const form = useForm<{ lfgRoleId: string; keywordPingsEnabled: boolean }>({ defaultValues: { lfgRoleId: data.settings.lfgRoleId || '', keywordPingsEnabled: data.settings.keywordPingsEnabled } });
  const mutation = useMutation({ mutationFn: (values: { lfgRoleId: string; keywordPingsEnabled: boolean }) => saveSettings(data.guild.id, { lfgRoleId: values.lfgRoleId || null, keywordPingsEnabled: values.keywordPingsEnabled }), onSuccess: () => { toast.success('Server settings saved'); refresh(); }, onError: (error: Error) => toast.error(error.message) });
  if (!data.guild.manageGuild) return <Empty icon={Settings} title="Manage Server required" copy="Discord’s Manage Server permission is required to change these settings." />;
  return <form onSubmit={form.handleSubmit((values) => mutation.mutate(values))} className="max-w-3xl space-y-5"><Card><CardHeader><CardTitle>Looking For Group</CardTitle><CardDescription>Choose the role mentioned by the `/party lfg` command.</CardDescription></CardHeader><CardContent><SelectField label="LFG role" value={form.watch('lfgRoleId')} onChange={(value) => form.setValue('lfgRoleId', value, { shouldDirty: true })}><option value="">No LFG role</option>{data.guild.roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</SelectField></CardContent></Card><Card><CardHeader><CardTitle>Keyword pings</CardTitle><CardDescription>Allow messages containing configured keywords to trigger their mapped ping groups.</CardDescription></CardHeader><CardContent><div className="flex items-center justify-between gap-6 rounded-xl border border-white/[.07] bg-white/[.02] p-4"><div><p className="font-medium text-white">Enable keyword matching</p><p className="mt-1 text-sm text-slate-500">Individual keywords are managed inside each ping group.</p></div><Switch checked={form.watch('keywordPingsEnabled')} onCheckedChange={(value) => form.setValue('keywordPingsEnabled', value, { shouldDirty: true })} /></div></CardContent></Card><div className="flex justify-end"><Button type="submit" disabled={!form.formState.isDirty || mutation.isPending}>{mutation.isPending && <LoaderCircle className="size-4 animate-spin" />}Save settings</Button></div></form>;
}

const emptyGroup: PingGroup = { name: '', roleId: '', allowedRoles: [], keywords: [] };
function PingGroups({ data, refresh }: { data: GuildData; refresh: () => void }) {
  const [groups, setGroups] = useState(data.settings.pingGroups);
  const [editing, setEditing] = useState<number | null>(null);
  const [draft, setDraft] = useState<PingGroup>(emptyGroup);
  useEffect(() => setGroups(data.settings.pingGroups), [data.settings.pingGroups]);
  const save = useMutation({ mutationFn: (next: PingGroup[]) => saveSettings(data.guild.id, { pingGroups: next }), onSuccess: () => { toast.success('Ping groups saved'); refresh(); }, onError: (error: Error) => toast.error(error.message) });
  if (!data.guild.manageGuild) return <Empty icon={BellRing} title="Manage Server required" copy="Discord’s Manage Server permission is required to manage ping groups." />;
  function open(group?: PingGroup, index?: number) { setDraft(group ? { ...group, allowedRoles: [...group.allowedRoles], keywords: [...group.keywords] } : emptyGroup); setEditing(index ?? -1); }
  function commit() { const next = editing === -1 ? [...groups, draft] : groups.map((group, index) => index === editing ? draft : group); setGroups(next); setEditing(null); save.mutate(next); }
  function remove(index: number) { const next = groups.filter((_, item) => item !== index); setGroups(next); save.mutate(next); }
  return <div className="space-y-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-display text-2xl text-white">Ping groups</h2><p className="mt-1 text-sm text-slate-400">Roles, permissions, and keyword triggers for `/party ping`.</p></div><Button onClick={() => open()}><Plus className="size-4" />Add ping group</Button></div>{groups.length ? <div className="grid gap-4 lg:grid-cols-2">{groups.map((group, index) => <Card key={`${group.name}-${index}`}><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle>{group.name}</CardTitle><CardDescription>{data.guild.roles.find((role) => role.id === group.roleId)?.name || 'Missing role'}</CardDescription></div><Badge>{group.keywords.length} keyword{group.keywords.length === 1 ? '' : 's'}</Badge></div></CardHeader><CardContent><div className="mb-5 flex flex-wrap gap-2">{group.keywords.length ? group.keywords.map((keyword) => <Badge key={keyword} className="border-white/10 bg-white/[.035] text-slate-300">{keyword}</Badge>) : <span className="text-sm text-slate-500">No keyword triggers</span>}</div><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => open(group, index)}>Edit</Button><Button size="sm" variant="destructive" onClick={() => remove(index)} aria-label={`Remove ${group.name}`}><Trash2 className="size-4" /></Button></div></CardContent></Card>)}</div> : <Empty icon={BellRing} title="No ping groups yet" copy="Create a group to give players a clear, permission-aware way to reach the right role." action={<Button onClick={() => open()}><Plus className="size-4" />Create first group</Button>} />}
  <Dialog open={editing !== null} onOpenChange={(open) => !open && setEditing(null)}><DialogContent><DialogHeader><DialogTitle>{editing === -1 ? 'Add ping group' : 'Edit ping group'}</DialogTitle><DialogDescription>Choose the pinged role, who can use it, and the words that trigger it.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label htmlFor="group-name">Name</Label><Input id="group-name" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="Boss hunts" maxLength={100} /></div><SelectField label="Ping role" value={draft.roleId} onChange={(value) => setDraft({ ...draft, roleId: value })}><option value="">Choose a role</option>{data.guild.roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</SelectField><div className="space-y-2"><Label htmlFor="allowed-roles">Allowed roles</Label><select id="allowed-roles" multiple className="select-field h-28 py-2" value={draft.allowedRoles} onChange={(event) => setDraft({ ...draft, allowedRoles: Array.from(event.target.selectedOptions, (option) => option.value) })}>{data.guild.roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select><p className="text-xs text-slate-500">Leave empty to let anyone use this group. Hold Ctrl/Cmd to select several.</p></div><div className="space-y-2"><Label htmlFor="group-keywords">Keywords</Label><Input id="group-keywords" value={draft.keywords.join(', ')} onChange={(event) => setDraft({ ...draft, keywords: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} placeholder="kraken, dark sea, boss" /></div></div><DialogFooter><Button variant="secondary" onClick={() => setEditing(null)}>Cancel</Button><Button onClick={commit} disabled={!draft.name.trim() || !draft.roleId || save.isPending}>Save group</Button></DialogFooter></DialogContent></Dialog></div>;
}

type DockValues = { name: string; description: string; publishMode: 'all' | 'manual'; accessMode: 'open' | 'request'; defaultLevel: string; gatekeeperRoleId: string; keywordsText: string };
function DockEditor({ guild, dock, open, onOpenChange, done }: { guild: Guild; dock: Dock | null; open: boolean; onOpenChange: (open: boolean) => void; done: () => void }) {
  const query = useQueryClient();
  const form = useForm<DockValues>({ defaultValues: { name: '', description: '', publishMode: 'manual', accessMode: 'open', defaultLevel: 'passive', gatekeeperRoleId: '', keywordsText: '' } });
  const [channels, setChannels] = useState<string[]>([]);
  useEffect(() => { form.reset({ name: dock?.name || '', description: dock?.description || '', publishMode: dock?.publishMode || 'manual', accessMode: dock?.accessMode || 'open', defaultLevel: dock?.defaultLevel || 'passive', gatekeeperRoleId: dock?.gatekeeperRoleId || '', keywordsText: dock?.keywords.join(', ') || '' }); setChannels(dock?.channelIds || []); }, [dock, open]);
  const mutation = useMutation({ mutationFn: (values: DockValues) => { const payload = { ...values, channelIds: channels, gatekeeperRoleId: values.gatekeeperRoleId || null, keywords: values.keywordsText.split(',').map((item) => item.trim()).filter(Boolean) }; return dock ? updateDock(guild.id, dock.id, payload) : createDock(guild.id, payload); }, onSuccess: () => { toast.success(dock ? 'Dock updated' : 'Dock published'); query.invalidateQueries({ queryKey: ['docks', guild.id] }); done(); onOpenChange(false); }, onError: (error: Error) => toast.error(error.message) });
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{dock ? 'Edit Dock' : 'Publish a Dock'}</DialogTitle><DialogDescription>Connect one or more source channels to the wider Sailor’s Lodge network.</DialogDescription></DialogHeader><form onSubmit={form.handleSubmit((values) => mutation.mutate(values))} className="space-y-4"><div className="space-y-2"><Label>Dock name</Label><Input {...form.register('name')} placeholder="Grand Navy Expeditions" /></div><div className="space-y-2"><Label>Description</Label><Textarea {...form.register('description')} placeholder="What should other communities expect here?" /></div><div className="space-y-2"><Label>Publishing channels</Label><div className="grid max-h-36 gap-1 overflow-auto rounded-xl border border-white/10 bg-black/20 p-2">{guild.channels.map((channel) => <label key={channel.id} className="flex cursor-pointer items-center gap-3 rounded-lg px-2 py-2 text-sm text-slate-300 hover:bg-white/[.04]"><input type="checkbox" checked={channels.includes(channel.id)} onChange={(event) => setChannels(event.target.checked ? [...channels, channel.id].slice(0, 10) : channels.filter((id) => id !== channel.id))} className="accent-teal-300" />#{channel.name}</label>)}</div></div><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Publish mode" value={form.watch('publishMode')} onChange={(value) => form.setValue('publishMode', value as 'all' | 'manual')}><option value="all">All messages</option><option value="manual">Manual with !p</option></SelectField><SelectField label="Who can follow" value={form.watch('accessMode')} onChange={(value) => form.setValue('accessMode', value as 'open' | 'request')}><option value="open">Open</option><option value="request">Request approval</option></SelectField><SelectField label="Default access" value={form.watch('defaultLevel')} onChange={(value) => form.setValue('defaultLevel', value)}>{dockLevels.slice(1).map((level) => <option key={level} value={level}>{levelLabels[level]}</option>)}</SelectField><SelectField label="Gatekeeper role" value={form.watch('gatekeeperRoleId')} onChange={(value) => form.setValue('gatekeeperRoleId', value)}><option value="">No gatekeeper role</option>{guild.roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</SelectField></div><div className="space-y-2"><Label>Ping keywords</Label><Input {...form.register('keywordsText')} placeholder="boss hunt, dark sea, expedition" /><p className="text-xs text-slate-500">Comma-separated, up to 25.</p></div><DialogFooter><Button type="button" variant="secondary" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={!channels.length || mutation.isPending}>{mutation.isPending && <LoaderCircle className="size-4 animate-spin" />}{dock ? 'Save changes' : 'Publish Dock'}</Button></DialogFooter></form></DialogContent></Dialog>;
}

function FollowEditor({ guild, dock, open, onOpenChange, done }: { guild: Guild; dock: Dock | null; open: boolean; onOpenChange: (open: boolean) => void; done: () => void }) {
  const [channelId, setChannelId] = useState(''); const [pingOwnServer, setPingOwnServer] = useState(true); const [pings, setPings] = useState<Record<string, string[]>>({});
  useEffect(() => { setChannelId(dock?.follow?.channelIds[0] || ''); setPingOwnServer(dock?.follow?.pingOwnServer !== false); setPings(dock?.follow?.keywordPings || {}); }, [dock, open]);
  const mutation = useMutation({ mutationFn: () => saveFollow(guild.id, dock!.id, { channelIds: [channelId], keywordPings: pings, pingOwnServer } as Partial<Follow>), onSuccess: () => { toast.success(dock?.follow ? 'Follow settings saved' : dock?.accessMode === 'request' ? 'Follow request sent' : 'Dock followed'); done(); onOpenChange(false); }, onError: (error: Error) => toast.error(error.message) });
  if (!dock) return null;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{dock.follow ? 'Configure follow' : `Follow ${dock.name}`}</DialogTitle><DialogDescription>Choose where messages arrive and which local roles each keyword should ping.</DialogDescription></DialogHeader><div className="space-y-4"><SelectField label="Receiving channel" value={channelId} onChange={setChannelId}><option value="">Choose a channel</option>{guild.channels.map((channel) => <option key={channel.id} value={channel.id}>#{channel.name}</option>)}</SelectField>{dock.keywords.map((keyword) => <div className="space-y-2" key={keyword}><Label>{keyword} roles</Label><select multiple className="select-field h-24 py-2" value={pings[keyword] || []} onChange={(event) => setPings({ ...pings, [keyword]: Array.from(event.target.selectedOptions, (option) => option.value) })}>{guild.roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></div>)}<div className="flex items-center justify-between rounded-xl border border-white/[.07] p-4"><div><p className="text-sm font-medium text-white">Ping this server’s own messages</p><p className="mt-1 text-xs text-slate-500">Apply keyword pings to messages originating here.</p></div><Switch checked={pingOwnServer} onCheckedChange={setPingOwnServer} /></div></div><DialogFooter><Button variant="secondary" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={() => mutation.mutate()} disabled={!channelId || mutation.isPending}>{mutation.isPending && <LoaderCircle className="size-4 animate-spin" />}Save follow</Button></DialogFooter></DialogContent></Dialog>;
}

function FollowersDialog({ guild, dock, open, onOpenChange }: { guild: Guild; dock: Dock | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  const queryClient = useQueryClient(); const query = useQuery({ queryKey: ['followers', guild.id, dock?.id], queryFn: () => getFollowers(guild.id, dock!.id), enabled: open && Boolean(dock) });
  const mutation = useMutation({ mutationFn: ({ id, level }: { id: string; level: string }) => setFollowerLevel(guild.id, dock!.id, id, level), onSuccess: () => { toast.success('Follower access updated'); queryClient.invalidateQueries({ queryKey: ['followers', guild.id, dock?.id] }); }, onError: (error: Error) => toast.error(error.message) });
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Followers of {dock?.name}</DialogTitle><DialogDescription>Approve requests and decide what every connected server can do.</DialogDescription></DialogHeader>{query.isLoading ? <Skeleton className="h-44" /> : query.error ? <ErrorState error={query.error} /> : query.data?.followers.length ? <div className="space-y-2">{query.data.followers.map((follower) => <div key={follower.guildId} className="flex flex-col gap-3 rounded-xl border border-white/[.07] p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="truncate font-medium text-white">{follower.guildName || follower.guildId}</p><p className="mt-1 text-xs text-slate-500">{follower.level === 'no-access' ? 'Waiting for approval' : 'Connected follower'}</p></div><select className="select-field w-full sm:w-48" value={follower.level} onChange={(event) => mutation.mutate({ id: follower.guildId, level: event.target.value })}>{dockLevels.map((level) => <option key={level} value={level}>{levelLabels[level]}</option>)}</select></div>)}</div> : <Empty icon={Users} title="No followers yet" copy="Servers that follow or request access will appear here." />}</DialogContent></Dialog>;
}

function BansPanel({ guild }: { guild: Guild }) {
  const queryClient = useQueryClient(); const query = useQuery({ queryKey: ['bans', guild.id], queryFn: () => getBans(guild.id) }); const [target, setTarget] = useState(''); const [reason, setReason] = useState('');
  const add = useMutation({ mutationFn: () => addBan(guild.id, target, reason), onSuccess: () => { toast.success('Server banned from published Docks'); setTarget(''); setReason(''); queryClient.invalidateQueries({ queryKey: ['bans', guild.id] }); }, onError: (error: Error) => toast.error(error.message) });
  const remove = useMutation({ mutationFn: (id: string) => removeBan(guild.id, id), onSuccess: () => { toast.success('Server unbanned'); queryClient.invalidateQueries({ queryKey: ['bans', guild.id] }); }, onError: (error: Error) => toast.error(error.message) });
  return <div className="space-y-4"><Card><CardHeader><CardTitle>Server bans</CardTitle><CardDescription>Block another known Sailor’s Lodge server from following any Dock published here.</CardDescription></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-[1fr_1.4fr_auto]"><Input value={target} onChange={(event) => setTarget(event.target.value)} placeholder="Discord server ID" /><Input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Reason" maxLength={500} /><Button variant="destructive" onClick={() => add.mutate()} disabled={!target || !reason || add.isPending}><ShieldBan className="size-4" />Ban</Button></div></CardContent></Card>{query.data?.bans.map((ban: Ban) => <div key={ban.targetGuildId} className="flex items-center gap-4 rounded-xl border border-rose-400/10 bg-rose-400/[.035] p-4"><div className="min-w-0 flex-1"><p className="font-medium text-white">{ban.targetGuildName || ban.targetGuildId}</p><p className="mt-1 truncate text-xs text-slate-500">{ban.reason}</p></div><Button size="sm" variant="secondary" onClick={() => remove.mutate(ban.targetGuildId)}>Unban</Button></div>)}</div>;
}

function DockCard({ guild, dock, view, edit, follow, followers, changed }: { guild: Guild; dock: Dock; view: string; edit: () => void; follow: () => void; followers: () => void; changed: () => void }) {
  const queryClient = useQueryClient(); const removeDockMutation = useMutation({ mutationFn: () => deleteDock(guild.id, dock.id), onSuccess: () => { toast.success('Dock deleted'); queryClient.invalidateQueries({ queryKey: ['docks', guild.id] }); changed(); }, onError: (error: Error) => toast.error(error.message) }); const unfollow = useMutation({ mutationFn: () => deleteFollow(guild.id, dock.id), onSuccess: () => { toast.success('Dock unfollowed'); queryClient.invalidateQueries({ queryKey: ['docks', guild.id] }); changed(); }, onError: (error: Error) => toast.error(error.message) });
  const own = dock.guildId === guild.id; const pending = dock.follow?.level === 'no-access';
  return <Card className="flex flex-col"><CardHeader><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="mb-2 flex flex-wrap gap-2">{dock.official && <Badge className="border-amber-200/20 bg-amber-300/10 text-amber-100">Official</Badge>}<Badge>{dock.accessMode === 'request' ? 'Request access' : 'Open'}</Badge>{pending && <Badge className="border-amber-200/20 bg-amber-300/10 text-amber-100">Pending</Badge>}</div><CardTitle className="truncate">{dock.name}</CardTitle><CardDescription className="mt-1">by {dock.guildName || dock.guildId}</CardDescription></div><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-teal-200/[.07] text-teal-200"><Anchor className="size-4" /></span></div></CardHeader><CardContent className="flex flex-1 flex-col"><p className="line-clamp-2 min-h-12 text-sm leading-6 text-slate-400">{dock.description || 'No description provided.'}</p><div className="mt-4 flex flex-wrap gap-1.5">{dock.keywords.slice(0, 4).map((keyword) => <Badge key={keyword} className="border-white/10 bg-white/[.03] text-slate-400">{keyword}</Badge>)}</div><div className="mt-5 flex items-center gap-4 border-t border-white/[.06] pt-4 text-xs text-slate-500"><span>{dock.followerCount} follower{dock.followerCount === 1 ? '' : 's'}</span><span>{dock.publishMode === 'all' ? 'All messages' : 'Manual !p'}</span></div><div className="mt-5 flex flex-wrap gap-2">{own ? <><Button size="sm" variant="secondary" onClick={edit}>Edit</Button><Button size="sm" variant="outline" onClick={followers}><Users className="size-4" />Followers</Button><Button size="sm" variant="destructive" onClick={() => confirm(`Delete ${dock.name} and disconnect every follower?`) && removeDockMutation.mutate()}><Trash2 className="size-4" /></Button></> : dock.follow ? <><Button size="sm" variant="secondary" onClick={follow}>Configure</Button><Button size="sm" variant="destructive" onClick={() => confirm(`Unfollow ${dock.name}?`) && unfollow.mutate()}>Unfollow</Button>{dock.follow.level === 'admin' && <Button size="sm" variant="outline" onClick={followers}>Followers</Button>}</> : <Button size="sm" onClick={follow}>Follow Dock</Button>}</div></CardContent></Card>;
}

function Docks({ data, refresh }: { data: GuildData; refresh: () => void }) {
  const [view, setView] = useState('discover'); const [search, setSearch] = useState(''); const [editing, setEditing] = useState<Dock | null | undefined>(); const [following, setFollowing] = useState<Dock | null>(null); const [managing, setManaging] = useState<Dock | null>(null);
  const queryClient = useQueryClient(); const query = useQuery({ queryKey: ['docks', data.guild.id, view, search], queryFn: () => getDocks(data.guild.id, view, search) });
  const docks = useMemo(() => view === 'following' ? (query.data?.docks || []).filter((dock) => dock.guildId !== data.guild.id) : query.data?.docks || [], [query.data, view, data.guild.id]);
  const changed = () => { queryClient.invalidateQueries({ queryKey: ['docks', data.guild.id] }); refresh(); };
  if (!data.guild.manageChannels) return <Empty icon={Network} title="Manage Channels required" copy="Discord’s Manage Channels permission is required to publish, follow, or administer Docks." />;
  return <div className="space-y-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h2 className="font-display text-2xl text-white">Dock network</h2><p className="mt-1 text-sm text-slate-400">Discover live boards and manage this server’s connections.</p></div><div className="flex flex-col gap-3 sm:flex-row"><div className="relative"><Search className="absolute left-3 top-3.5 size-4 text-slate-500" /><Input className="pl-10 sm:w-64" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search Docks" /></div><Button onClick={() => setEditing(null)}><Plus className="size-4" />Publish Dock</Button></div></div><div className="flex flex-wrap gap-2 border-b border-white/[.07] pb-4">{['discover', 'published', 'following', 'bans'].map((item) => <Button key={item} size="sm" variant={view === item ? 'outline' : 'ghost'} onClick={() => setView(item)} className="capitalize">{item}</Button>)}</div>{view === 'bans' ? <BansPanel guild={data.guild} /> : query.isLoading ? <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{[1, 2, 3].map((item) => <Skeleton key={item} className="h-72" />)}</div> : query.error ? <ErrorState error={query.error} retry={() => query.refetch()} /> : docks.length ? <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{docks.map((dock) => <DockCard key={dock.id} guild={data.guild} dock={dock} view={view} edit={() => setEditing(dock)} follow={() => setFollowing(dock)} followers={() => setManaging(dock)} changed={changed} />)}</div> : <Empty icon={ShipWheel} title={search ? 'No Docks matched' : view === 'published' ? 'No published Docks' : view === 'following' ? 'Not following any Docks' : 'No Docks available'} copy={search ? 'Try a different name, publisher, or description.' : view === 'published' ? 'Publish a channel so other communities can discover and follow it.' : 'Browse the directory or publish the first Dock.'} action={view === 'published' ? <Button onClick={() => setEditing(null)}><Plus className="size-4" />Publish Dock</Button> : undefined} />}
  <DockEditor guild={data.guild} dock={editing || null} open={editing !== undefined} onOpenChange={(open) => !open && setEditing(undefined)} done={changed} /><FollowEditor guild={data.guild} dock={following} open={Boolean(following)} onOpenChange={(open) => !open && setFollowing(null)} done={changed} /><FollowersDialog guild={data.guild} dock={managing} open={Boolean(managing)} onOpenChange={(open) => !open && setManaging(null)} /></div>;
}

export function Dashboard() {
  const path = usePath(); const [, , guildId, requestedSection] = path.split('/'); const section = requestedSection || 'overview'; const me = useQuery({ queryKey: ['me'], queryFn: getMe }); const guilds = useQuery({ queryKey: ['guilds'], queryFn: getGuilds, enabled: Boolean(me.data) }); const data = useQuery({ queryKey: ['guild', guildId], queryFn: () => getGuild(guildId!), enabled: Boolean(me.data && guildId) });
  if (me.isLoading || (me.data && guilds.isLoading) || (guildId && data.isLoading)) return <div className="grid min-h-screen place-items-center bg-[#061217] text-teal-200"><LoaderCircle className="size-7 animate-spin" /><span className="sr-only">Loading dashboard</span></div>;
  if (me.error instanceof ApiError && me.error.status === 401) return <div className="grid min-h-screen place-items-center bg-[#061217] px-5 text-center text-white"><Card className="max-w-md p-8"><span className="mx-auto grid size-12 place-items-center rounded-xl bg-teal-200/[.08] text-teal-200"><DoorOpen className="size-5" /></span><h1 className="mt-5 font-display text-3xl">Come aboard</h1><p className="mt-3 text-sm leading-6 text-slate-400">Sign in with Discord to see servers where you can manage Sailor’s Lodge.</p><Button asChild className="mt-6 w-full"><a href="/auth/discord">Continue with Discord</a></Button><Button asChild variant="ghost" className="mt-2 w-full"><Link to="/">Back to home</Link></Button></Card></div>;
  if (me.error) return <div className="min-h-screen bg-[#061217] p-8 text-white"><ErrorState error={me.error} /></div>;
  if (!guildId) return <ServerChooser guilds={guilds.data?.guilds || []} />;
  if (data.error) return <div className="min-h-screen bg-[#061217] p-8 text-white"><ErrorState error={data.error} /><Button asChild variant="ghost" className="mt-4"><Link to="/dashboard">Choose another server</Link></Button></div>;
  if (!data.data || !me.data) return null;
  if (!sections.some((item) => item.id === section)) { navigate(`/dashboard/${guildId}/overview`, true); return null; }
  const refresh = () => data.refetch();
  return <Shell user={me.data.user} guilds={guilds.data?.guilds || []} data={data.data} section={section}><>{section === 'overview' && <Overview data={data.data} />}{section === 'settings' && <ServerSettings data={data.data} refresh={refresh} />}{section === 'pings' && <PingGroups data={data.data} refresh={refresh} />}{section === 'docks' && <Docks data={data.data} refresh={refresh} />}</></Shell>;
}
